import axios from 'axios';
import Head from 'next/head';
import { useState } from 'react';
import ListOfProducts from '../components/ListOfProducts';
import AddProductButton from '../components/AddProductButton';
import AddProductModal from '../components/AddProductModal';

export default function Home({products, isAdmin}) {
  // const products = data.data;
  const [modalIsOpen, setModalIsOpen] = useState(false);
  return (
    <div className="c-home">
      <Head>
        <title>Products Ordering app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Hero/> */}
      {isAdmin && <AddProductButton setModalIsOpen={setModalIsOpen}/>}
      <ListOfProducts products={products} />
      {modalIsOpen && <AddProductModal setModalIsOpen={setModalIsOpen}/>}
    </div>
  );
};

/* Retrieves product(s) data from mongodb database */
/* export async function getServerSideProps() {
  await dbConnect();
  // find all the data in our database
  const result = await Product.find({});
  const products = result.map((doc) => {
    const product = doc.toObject();
    product._id = product._id.toString();
    return product;
  });
  return { props: { products: products } };
};*/

/* Axios: Retrieves product(s) data from mongodb database */
export async function getServerSideProps(ctx) {

  const adminCookie = ctx.req?.cookies || '';
  let isAdmin = false;
  if (adminCookie.token === process.env.TOKEN) {
    isAdmin = true;
  }


  const res = await axios.get('http://localhost:3000/api/products');
  return {
    props: {
      products: res.data.data,
      isAdmin
    }
  };
};
