import axios from 'axios';
import Head from 'next/head';
import Hero from '../components/Hero';
import ListOfProducts from '../components/ListOfProducts';
import Image from 'next/image';

export default function Home({data}) {
  const products = data.data;
  return (
    <div className="c-home">
      <Head>
        <title>Products Ordering app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <ListOfProducts products={products} />
    </div>
  );
};

/* Retrieves product(s) data from mongodb database */
/* export async function getServerSideProps() {
  await dbConnect();
  // find all the data in our database
  const result = await Product.find({});
  const products = result.map((doc) => {
    const product = doc.toObject();
    product._id = product._id.toString();
    return product;
  });
  return { props: { products: products } };
};*/

/* Axios: Retrieves product(s) data from mongodb database */
export async function getServerSideProps() {
  const res = await axios.get('http://localhost:3000/api/products');
  return {
    props: {
      data: res.data,
    }
  };
};
